### PR TITLE
Update to fontawesome 6

### PR DESCRIPTION
**Pull request by dcermak**
This PR changes how fontawesome is installed, instead of vendoring it in git, it is now installed via npm and moved into `build/webfonts`. This allows us to switch to version 6 and add new icons:

image

### CODE REVIEW

**Comment by cboltz** [comment]
Currently the landing-page gets deployed by a simple `git clone` or `git pull` without any post-processing (no npm calls etc.)

Therefore I have a feeling that this PR will break things (unless we also change how we do the deployment).

**Comment by dcermak** [comment]
> Currently the landing-page gets deployed by a simple `git clone` or `git pull` without any post-processing (no npm calls etc.)
> 
> Therefore I have a feeling that this PR will break things (unless we also change how we do the deployment).

It most certainly will then! Let me fix this.

**Comment by ddemaio** [comment]
@cboltz do you think this is good to merge?

**Comment by ddemaio** [comment]
Thank you @dcermak

**Pull request merged**
