### PR TITLE
Fix mixed content error caused by loading insecure fonts

### PR DESCRIPTION
**Pull request by koenwoortman**
Fixes the following error:

Mixed Content: The page at 'https://www.opensuse.org/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/sourcesanspro/v11/6xKydSBYKcSV-LCoeQqfX1RYOo3i94_wlxdr.ttf'. This request has been blocked; the content must be served over HTTPS.

### CODE REVIEW

**Review by cyntss — APPROVED** [review]

**Comment by cyntss** [comment]
Looks good @koenwoortman !

Btw, I don't know how we are deploying this page but it would be good if someone could take care of moving the build system to run on deploy time. This way we don't need to track the `build` folder anymore, which would save us a lot of merge conflicts.

**Comment by cboltz** [comment]
> Btw, I don't know how we are deploying this page but it would be good if someone could take care of moving the build system to run on deploy time. This way we don't need to track the build folder anymore, which would save us a lot of merge conflicts.

AFAIK the current implementation is a simple "git pull" cronjob on the webserver. Before we can change that, we have to move www.o.o to a VM in Nuremberg and, to make things more interesting[tm], find out how to handle `/openid/`.

That said - can you please resolve the merge conflicts?

**Comment by cyntss** [comment]
> AFAIK the current implementation is a simple "git pull" cronjob on the webserver. Before we can change that, we have to move www.o.o to a VM in Nuremberg and, to make things more interesting[tm], find out how to handle /openid/.

We could give it a second instruction to run `gulp build` after `git pull` has finished. Just an idea.

**Comment by cboltz** [comment]
> We could give it a second instruction to run gulp build after git pull has finished. Just an idea.

We could, if it wouldn't run on a server in Provo... (if you want to know the long version, ask me @ oSC ;-)

**Pull request closed without merging**
