### PR TITLE
Update lt.json

### PR DESCRIPTION
**Pull request by embar-**

### CODE REVIEW

**Comment by coolo** [comment]
This conflicts with https://github.com/openSUSE/landing-page/pull/72 - unless you already did, please track this in SVN

**Comment by embar-** [comment]
Updated in SVN. 
P.S. I see, in SVN there is no longer messages about Machinery.

**Comment by coolo** [comment]
it's removed from index.html too :)

**Comment by ddemaio** [comment]
@cyntss I noticed the news section reverted back to original design and doesn't update

**Comment by coolo** [comment]
look at https://wwwstage.opensuse.org/ - www.opensuse.org wasn't deployed in a while

**Comment by coolo** [comment]
(and don't hijack random pull request)

**Pull request closed without merging**
