### PR TITLE
remove languages with missing translations

### PR DESCRIPTION
**Pull request by skriesch**
- compared finished translations on Weblate with existing languages
- removing languages 
- https://progress.opensuse.org/issues/17020

### CODE REVIEW

**Comment by lnussel** [comment]
Greek? Are you sure?

**Comment by skriesch** [comment]
That's the Greek translation status: https://l10n.opensuse.org/projects/landing-page/master/el/
Additional to that I know about the Greek Coordinator that he is on tour at the moment.

**Comment by skriesch** [comment]
Greek is translated today. It is added again.

**Comment by lnussel** [comment]
so we didn't do this after all. thanks anyways!

**Pull request closed without merging**
